# Documentation: .gitlab/ci/README.md#manifest-file-to-control-the-buildtest-apps

tools/test_apps/peripherals/i2c_wifi:
  disable:
    - if: SOC_I2C_SUPPORTED != 1 or SOC_WIFI_SUPPORTED != 1
  disable_test:
    - if: IDF_TARGET in ["esp32c5"]
      reason: leak of runner
