# Documentation: .gitlab/ci/README.md#manifest-file-to-control-the-buildtest-apps

examples/storage/fatfs:
  depends_components:
    - fatfs
    - vfs
  disable_test:
    - if: IDF_TARGET != "esp32"
      reason: only one target needed
